repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        entry: npx prettier --check .
        language: system
        types: [ts]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.54.0
    hooks:
      - id: eslint
        entry: npx eslint .
        language: system
        types: [ts]

  - repo: local
    hooks:
      - id: deno-lint
        name: Deno Lint
        entry: deno lint
        language: system
        types: [ts]
      - id: deno-format
        name: Deno Format
        entry: deno fmt --check
        language: system
        types: [ts]
